# Generated by Django 5.2.11 on 2026-02-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(blank=True, max_length=255)),
                ('symptoms', models.TextField()),
                ('symptom_start_date', models.DateField(blank=True, null=True)),
                ('symptom_start_time', models.TimeField(blank=True, null=True)),
                ('severity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doctor_questions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('medication_taken', models.TextField(blank=True)),
                ('source_language', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('translated_symptoms', models.TextField(blank=True)),
                ('translated_questions', models.TextField(blank=True)),
                ('translated_notes', models.TextField(blank=True)),
                ('translated_medication_taken', models.TextField(blank=True)),
                ('patient_name', models.CharField(blank=True, max_length=150)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_allergies', models.TextField(blank=True)),
                ('patient_medications', models.TextField(blank=True)),
                ('patient_surgeries', models.TextField(blank=True)),
                ('translated_patient_name', models.TextField(blank=True)),
                ('translated_patient_dob', models.TextField(blank=True)),
                ('translated_patient_allergies', models.TextField(blank=True)),
                ('translated_patient_medications', models.TextField(blank=True)),
                ('translated_patient_surgeries', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('surgeries', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
