name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version compatible with your project

      - name: Install dependencies
        run: |
          cd lanmed-frontend
          npm install

      - name: Build Project
        run: |
          cd lanmed-frontend
          npm run build

      - name: Debug Output (List build directory)
        run: |
          cd lanmed-frontend
          ls -la

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BAY_0020B761E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # For GitHub integrations (PR comments)
          action: "upload"
          
          ###### Adjust the paths below to match your project structure ######
          app_location: "./lanmed-frontend"  # Source path to your app code
          output_location: "dist"  # Change to 'dist', '.next', or 'build' based on your framework
          api_location: ""  # Optional - path to API (if applicable)
          ###### End of Configuration ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BAY_0020B761E }}
          action: "close"
